//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 09:17:50 PDT 
//


package org.imayam.rss;


/**
 * Java content class for guid element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/jwsdp-1.4/jaxb/bin/rss2.xsd line 25)
 * <p>
 * <pre>
 * &lt;element name="guid">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyURI">
 *     &lt;enumeration value="http://liftoff.msfc.nasa.gov/2003/05/20.html#item570"/>
 *     &lt;enumeration value="http://liftoff.msfc.nasa.gov/2003/05/27.html#item571"/>
 *     &lt;enumeration value="http://liftoff.msfc.nasa.gov/2003/05/30.html#item572"/>
 *     &lt;enumeration value="http://liftoff.msfc.nasa.gov/2003/06/03.html#item573"/>
 *   &lt;/restriction>
 * &lt;/element>
 * </pre>
 * 
 */
public interface Guid
    extends javax.xml.bind.Element
{


    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getValue();

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setValue(java.lang.String value);

}
