//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 09:25:18 PDT 
//


package org.imayam.rss;


/**
 * Java content class for link element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/jwsdp-1.4/jaxb/bin/rss2.xsd line 35)
 * <p>
 * <pre>
 * &lt;element name="link">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyURI">
 *     &lt;enumeration value="http://tamil.galatta.com/"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8867/rss/1/news/Trisha.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8868/rss/1/news/Deepavali.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8869/rss/1/news/Madhavan.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8880/rss/1/news/sivaji.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8881/rss/1/news/sneha.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8882/rss/1/news/Kangana.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8883/rss/1/news/Suriya.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8886/rss/1/news/Kaadhal.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8887/rss/1/news/Vijay.html"/>
 *     &lt;enumeration value="http://tamil.galatta.com/entertainment/livewire/livewire/id/8891/rss/1/news/Vikranth.html"/>
 *   &lt;/restriction>
 * &lt;/element>
 * </pre>
 * 
 */
public interface Link
    extends javax.xml.bind.Element
{


    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getValue();

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setValue(java.lang.String value);

}
