//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 09:25:18 PDT 
//


package org.imayam.rss;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imayam.rss package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends org.imayam.rss.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(17, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static org.imayam.rss.impl.runtime.GrammarInfo grammarInfo = new org.imayam.rss.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (org.imayam.rss.ObjectFactory.class));
    public final static java.lang.Class version = (org.imayam.rss.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((org.imayam.rss.Link.class), "org.imayam.rss.impl.LinkImpl");
        defaultImplementations.put((org.imayam.rss.Channel.class), "org.imayam.rss.impl.ChannelImpl");
        defaultImplementations.put((org.imayam.rss.Title.class), "org.imayam.rss.impl.TitleImpl");
        defaultImplementations.put((org.imayam.rss.Rss.class), "org.imayam.rss.impl.RssImpl");
        defaultImplementations.put((org.imayam.rss.ChannelType.class), "org.imayam.rss.impl.ChannelTypeImpl");
        defaultImplementations.put((org.imayam.rss.RssType.class), "org.imayam.rss.impl.RssTypeImpl");
        defaultImplementations.put((org.imayam.rss.ItemType.class), "org.imayam.rss.impl.ItemTypeImpl");
        defaultImplementations.put((org.imayam.rss.Url.class), "org.imayam.rss.impl.UrlImpl");
        defaultImplementations.put((org.imayam.rss.Item.class), "org.imayam.rss.impl.ItemImpl");
        defaultImplementations.put((org.imayam.rss.ImageType.class), "org.imayam.rss.impl.ImageTypeImpl");
        defaultImplementations.put((org.imayam.rss.Image.class), "org.imayam.rss.impl.ImageImpl");
        defaultImplementations.put((org.imayam.rss.Description.class), "org.imayam.rss.impl.DescriptionImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "item"), (org.imayam.rss.Item.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rss"), (org.imayam.rss.Rss.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "title"), (org.imayam.rss.Title.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "description"), (org.imayam.rss.Description.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "image"), (org.imayam.rss.Image.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "url"), (org.imayam.rss.Url.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "link"), (org.imayam.rss.Link.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "channel"), (org.imayam.rss.Channel.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imayam.rss
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Link
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Link createLink()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.LinkImpl();
    }

    /**
     * Create an instance of Link
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Link createLink(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.LinkImpl(value);
    }

    /**
     * Create an instance of Channel
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Channel createChannel()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.ChannelImpl();
    }

    /**
     * Create an instance of Title
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Title createTitle()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.TitleImpl();
    }

    /**
     * Create an instance of Title
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Title createTitle(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.TitleImpl(value);
    }

    /**
     * Create an instance of Rss
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Rss createRss()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.RssImpl();
    }

    /**
     * Create an instance of ChannelType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.ChannelType createChannelType()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.ChannelTypeImpl();
    }

    /**
     * Create an instance of RssType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.RssType createRssType()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.RssTypeImpl();
    }

    /**
     * Create an instance of ItemType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.ItemType createItemType()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.ItemTypeImpl();
    }

    /**
     * Create an instance of Url
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Url createUrl()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.UrlImpl();
    }

    /**
     * Create an instance of Url
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Url createUrl(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.UrlImpl(value);
    }

    /**
     * Create an instance of Item
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Item createItem()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.ItemImpl();
    }

    /**
     * Create an instance of ImageType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.ImageType createImageType()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.ImageTypeImpl();
    }

    /**
     * Create an instance of Image
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Image createImage()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.ImageImpl();
    }

    /**
     * Create an instance of Description
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Description createDescription()
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.DescriptionImpl();
    }

    /**
     * Create an instance of Description
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.imayam.rss.Description createDescription(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.imayam.rss.impl.DescriptionImpl(value);
    }

}
