//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 09:25:18 PDT 
//


package org.imayam.rss;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/jwsdp-1.4/jaxb/bin/rss2.xsd line 53)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}channel"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface RssType {


    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal}
     */
    java.math.BigDecimal getVersion();

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal}
     */
    void setVersion(java.math.BigDecimal value);

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link org.imayam.rss.ChannelType}
     *     {@link org.imayam.rss.Channel}
     */
    org.imayam.rss.ChannelType getChannel();

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.imayam.rss.ChannelType}
     *     {@link org.imayam.rss.Channel}
     */
    void setChannel(org.imayam.rss.ChannelType value);

}
