//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 09:25:18 PDT 
//


package org.imayam.rss.impl;

public class ChannelTypeImpl implements org.imayam.rss.ChannelType, com.sun.xml.bind.JAXBObject, org.imayam.rss.impl.runtime.UnmarshallableObject, org.imayam.rss.impl.runtime.XMLSerializable, org.imayam.rss.impl.runtime.ValidatableObject
{

    protected java.lang.String _Link;
    protected org.imayam.rss.ImageType _Image;
    protected java.lang.String _Description;
    protected com.sun.xml.bind.util.ListImpl _Item;
    protected java.lang.String _Title;
    public final static java.lang.Class version = (org.imayam.rss.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.imayam.rss.ChannelType.class);
    }

    public java.lang.String getLink() {
        return _Link;
    }

    public void setLink(java.lang.String value) {
        _Link = value;
    }

    public org.imayam.rss.ImageType getImage() {
        return _Image;
    }

    public void setImage(org.imayam.rss.ImageType value) {
        _Image = value;
    }

    public java.lang.String getDescription() {
        return _Description;
    }

    public void setDescription(java.lang.String value) {
        _Description = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getItem() {
        if (_Item == null) {
            _Item = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _Item;
    }

    public java.util.List getItem() {
        return _getItem();
    }

    public java.lang.String getTitle() {
        return _Title;
    }

    public void setTitle(java.lang.String value) {
        _Title = value;
    }

    public org.imayam.rss.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.imayam.rss.impl.runtime.UnmarshallingContext context) {
        return new org.imayam.rss.impl.ChannelTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(org.imayam.rss.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx4 = 0;
        final int len4 = ((_Item == null)? 0 :_Item.size());
        context.startElement("", "title");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Title), "Title");
        } catch (java.lang.Exception e) {
            org.imayam.rss.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "link");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Link), "Link");
        } catch (java.lang.Exception e) {
            org.imayam.rss.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "description");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Description), "Description");
        } catch (java.lang.Exception e) {
            org.imayam.rss.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_Image instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Image), "Image");
        } else {
            context.startElement("", "image");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Image), "Image");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Image), "Image");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Image), "Image");
            context.endElement();
        }
        while (idx4 != len4) {
            if (_Item.get(idx4) instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Item.get(idx4 ++)), "Item");
            } else {
                context.startElement("", "item");
                int idx_8 = idx4;
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Item.get(idx_8 ++)), "Item");
                context.endNamespaceDecls();
                int idx_9 = idx4;
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Item.get(idx_9 ++)), "Item");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Item.get(idx4 ++)), "Item");
                context.endElement();
            }
        }
    }

    public void serializeAttributes(org.imayam.rss.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx4 = 0;
        final int len4 = ((_Item == null)? 0 :_Item.size());
        if (_Image instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Image), "Image");
        }
        while (idx4 != len4) {
            if (_Item.get(idx4) instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Item.get(idx4 ++)), "Item");
            } else {
                idx4 += 1;
            }
        }
    }

    public void serializeURIs(org.imayam.rss.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx4 = 0;
        final int len4 = ((_Item == null)? 0 :_Item.size());
        if (_Image instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Image), "Image");
        }
        while (idx4 != len4) {
            if (_Item.get(idx4) instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Item.get(idx4 ++)), "Item");
            } else {
                idx4 += 1;
            }
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.imayam.rss.ChannelType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun.msv."
+"grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/su"
+"n/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq"
+"\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002"
+"dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001d"
+"Lcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.datatyp"
+"e.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.d"
+"atatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.data"
+"type.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd"
+".XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/Strin"
+"g;L\u0000\btypeNameq\u0000~\u0000\u0016L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/"
+"WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006"
+"stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Prese"
+"rve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcess"
+"or\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetEx"
+"pression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t"
+"\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0016L\u0000\fnamespaceURIq\u0000~\u0000\u0016xpq\u0000~\u0000\u001aq\u0000~\u0000\u0019sr"
+"\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.su"
+"n.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClass"
+"q\u0000~\u0000\nxq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000"
+"\u000eppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0013q\u0000"
+"~\u0000\u0019t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$"
+"Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001cq\u0000~\u0000\u001fsq\u0000~\u0000 q\u0000~\u0000+q\u0000~\u0000\u0019sr\u0000#com.sun.ms"
+"v.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0016L\u0000\fname"
+"spaceURIq\u0000~\u0000\u0016xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt"
+"\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000com.su"
+"n.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003s"
+"q\u0000~\u0000&\u0001psq\u0000~\u0000/t\u0000\u0005titlet\u0000\u0000sq\u0000~\u0000\tpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000eppsr\u0000)com.sun"
+".msv.datatype.xsd.EnumerationFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006valuest\u0000\u000fLja"
+"va/util/Set;xr\u00009com.sun.msv.datatype.xsd.DataTypeWithValueCo"
+"nstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTyp"
+"eWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\b"
+"baseTypet\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;L\u0000\fconcr"
+"eteTypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNam"
+"eq\u0000~\u0000\u0016xq\u0000~\u0000\u0015q\u0000~\u00009pq\u0000~\u0000-\u0000\u0000sr\u0000#com.sun.msv.datatype.xsd.AnyURI"
+"Type\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0013q\u0000~\u0000\u0019t\u0000\u0006anyURIq\u0000~\u0000-q\u0000~\u0000Et\u0000\u000benumerations"
+"r\u0000\u0011java.util.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u000bt\u0000Xhttp://tam"
+"il.galatta.com/entertainment/livewire/livewire/id/8882/rss/1"
+"/news/Kangana.htmlt\u0000Whttp://tamil.galatta.com/entertainment/"
+"livewire/livewire/id/8867/rss/1/news/Trisha.htmlt\u0000\u0019http://ta"
+"mil.galatta.com/t\u0000Yhttp://tamil.galatta.com/entertainment/li"
+"vewire/livewire/id/8869/rss/1/news/Madhavan.htmlt\u0000Vhttp://ta"
+"mil.galatta.com/entertainment/livewire/livewire/id/8881/rss/"
+"1/news/sneha.htmlt\u0000Zhttp://tamil.galatta.com/entertainment/l"
+"ivewire/livewire/id/8868/rss/1/news/Deepavali.htmlt\u0000Xhttp://"
+"tamil.galatta.com/entertainment/livewire/livewire/id/8886/rs"
+"s/1/news/Kaadhal.htmlt\u0000Whttp://tamil.galatta.com/entertainme"
+"nt/livewire/livewire/id/8883/rss/1/news/Suriya.htmlt\u0000Whttp:/"
+"/tamil.galatta.com/entertainment/livewire/livewire/id/8880/r"
+"ss/1/news/sivaji.htmlt\u0000Yhttp://tamil.galatta.com/entertainme"
+"nt/livewire/livewire/id/8891/rss/1/news/Vikranth.htmlt\u0000Vhttp"
+"://tamil.galatta.com/entertainment/livewire/livewire/id/8887"
+"/rss/1/news/Vijay.htmlxq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u000eanyURI-derivedq\u0000~\u00009sq\u0000~"
+"\u0000\"ppsq\u0000~\u0000$q\u0000~\u0000\'pq\u0000~\u0000(q\u0000~\u00001q\u0000~\u00005sq\u0000~\u0000/t\u0000\u0004linkq\u0000~\u00009sq\u0000~\u0000\tpp\u0000sq"
+"\u0000~\u0000\u0000ppq\u0000~\u0000\u0011sq\u0000~\u0000\"ppsq\u0000~\u0000$q\u0000~\u0000\'pq\u0000~\u0000(q\u0000~\u00001q\u0000~\u00005sq\u0000~\u0000/t\u0000\u000bdescr"
+"iptionq\u0000~\u00009sq\u0000~\u0000\"ppsq\u0000~\u0000\tpp\u0000sq\u0000~\u0000\"ppsr\u0000 com.sun.msv.grammar."
+"OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\'psq\u0000~\u0000$q\u0000~\u0000\'psr\u00002com.sun.msv.gra"
+"mmar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u00006psr"
+"\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00000q\u0000~\u00005sq\u0000~"
+"\u0000/t\u0000\u0014org.imayam.rss.Imaget\u0000+http://java.sun.com/jaxb/xjc/dum"
+"my-elementssq\u0000~\u0000\tpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\tpp\u0000sq\u0000~\u0000\"ppsq\u0000~\u0000dq\u0000~\u0000\'psq\u0000"
+"~\u0000$q\u0000~\u0000\'pq\u0000~\u0000iq\u0000~\u0000kq\u0000~\u00005sq\u0000~\u0000/t\u0000\u0018org.imayam.rss.ImageTypeq\u0000~"
+"\u0000nsq\u0000~\u0000\"ppsq\u0000~\u0000$q\u0000~\u0000\'pq\u0000~\u0000(q\u0000~\u00001q\u0000~\u00005sq\u0000~\u0000/t\u0000\u0005imageq\u0000~\u00009sq\u0000~"
+"\u0000dppsq\u0000~\u0000\"ppsq\u0000~\u0000\tpp\u0000sq\u0000~\u0000\"ppsq\u0000~\u0000dq\u0000~\u0000\'psq\u0000~\u0000$q\u0000~\u0000\'pq\u0000~\u0000iq\u0000"
+"~\u0000kq\u0000~\u00005sq\u0000~\u0000/t\u0000\u0013org.imayam.rss.Itemq\u0000~\u0000nsq\u0000~\u0000\tpp\u0000sq\u0000~\u0000\u0000ppsq"
+"\u0000~\u0000\tpp\u0000sq\u0000~\u0000\"ppsq\u0000~\u0000dq\u0000~\u0000\'psq\u0000~\u0000$q\u0000~\u0000\'pq\u0000~\u0000iq\u0000~\u0000kq\u0000~\u00005sq\u0000~\u0000/"
+"t\u0000\u0017org.imayam.rss.ItemTypeq\u0000~\u0000nsq\u0000~\u0000\"ppsq\u0000~\u0000$q\u0000~\u0000\'pq\u0000~\u0000(q\u0000~\u0000"
+"1q\u0000~\u00005sq\u0000~\u0000/t\u0000\u0004itemq\u0000~\u00009sr\u0000\"com.sun.msv.grammar.ExpressionPo"
+"ol\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPo"
+"ol$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$Close"
+"dHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun"
+"/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0019\u0001pq\u0000~\u0000cq\u0000~\u0000rq\u0000~\u0000~q\u0000~\u0000\u0086q\u0000~\u0000"
+";q\u0000~\u0000{q\u0000~\u0000\u0005q\u0000~\u0000#q\u0000~\u0000Wq\u0000~\u0000]q\u0000~\u0000wq\u0000~\u0000\u008bq\u0000~\u0000\rq\u0000~\u0000\\q\u0000~\u0000pq\u0000~\u0000\u0084q\u0000~\u0000"
+"fq\u0000~\u0000sq\u0000~\u0000\u007fq\u0000~\u0000\u0087q\u0000~\u0000\u0006q\u0000~\u0000aq\u0000~\u0000|q\u0000~\u0000\u0007q\u0000~\u0000\bx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.imayam.rss.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.imayam.rss.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------");
        }

        protected Unmarshaller(org.imayam.rss.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.imayam.rss.impl.ChannelTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  10 :
                        if (("title" == ___local)&&("" == ___uri)) {
                            _Image = ((org.imayam.rss.impl.ImageTypeImpl) spawnChildFromEnterElement((org.imayam.rss.impl.ImageTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  3 :
                        if (("link" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  0 :
                        if (("title" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("item" == ___local)&&("" == ___uri)) {
                            _getItem().add(((org.imayam.rss.impl.ItemImpl) spawnChildFromEnterElement((org.imayam.rss.impl.ItemImpl.class), 13, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("item" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 14;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("title" == ___local)&&("" == ___uri)) {
                            _getItem().add(((org.imayam.rss.impl.ItemTypeImpl) spawnChildFromEnterElement((org.imayam.rss.impl.ItemTypeImpl.class), 15, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  9 :
                        if (("image" == ___local)&&("" == ___uri)) {
                            _Image = ((org.imayam.rss.impl.ImageImpl) spawnChildFromEnterElement((org.imayam.rss.impl.ImageImpl.class), 12, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("image" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 10;
                            return ;
                        }
                        break;
                    case  13 :
                        if (("item" == ___local)&&("" == ___uri)) {
                            _getItem().add(((org.imayam.rss.impl.ItemImpl) spawnChildFromEnterElement((org.imayam.rss.impl.ItemImpl.class), 13, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("item" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 14;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  6 :
                        if (("description" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  5 :
                        if (("link" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("description" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("image" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("item" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 13;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("title" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  13 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  13 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  13 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  4 :
                            eatText1(value);
                            state = 5;
                            return ;
                        case  1 :
                            eatText2(value);
                            state = 2;
                            return ;
                        case  7 :
                            eatText3(value);
                            state = 8;
                            return ;
                        case  13 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Link = com.sun.xml.bind.WhiteSpaceProcessor.collapse(value);
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Title = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Description = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
